export const ADD_FRIENDS = 'ADD_FRIENDS';
export const EDIT_FRIENDS = 'EDIT_FRIENDS';
export const DELETE_FRIENDS = 'DELETE_FRIENDS';
export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const ON_FRIENDS_INPUT_CHANGE = 'ON_FRIENDS_INPUT_CHANGE';
export const ON_SUBMIT = 'ON_VALUE_CHANGE';